# Generated by Django 4.2.4 on 2024-03-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database_handler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount", old_name="isActive", new_name="is_active",
        ),
        migrations.RenameField(
            model_name="useraccount", old_name="isStaff", new_name="is_staff",
        ),
    ]
