# Generated by Django 4.2.4 on 2024-03-19 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database_handler", "0002_rename_isactive_useraccount_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["image_id"],},
        ),
    ]
