# Generated by Django 4.2.4 on 2024-03-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database_handler", "0003_patientimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientimage", old_name="user_id", new_name="user",
        ),
    ]
