# Generated by Django 4.2.4 on 2024-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_handler", "0004_rename_user_id_patientimage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientimage",
            name="classification",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
